### ISSUE TITLE
Links with +tab+ inconsistent between PFE and FEM

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/markdownz#102]
This issue might move to FEM, PFE, or stay in this repo.

The Zooniverse Markdown help modal notes links with `[+tab+zooniverse](+tab+https://www.zooniverse.org)` will open in a new tab. This works as described in PFE, but in FEM noted links do not open at all. In FEM all links (without `+tab+`) open in a new tab.

To demonstrate, scroll to the project introduction, look for "Link test:", and click the links:
- PFE: https://www.zooniverse.org/projects/markbouslog/test-project-mb
- FEM: https://frontend.preview.zooniverse.org/projects/markbouslog/test-project-mb
- related project lab, if you'd like to edit/add: https://www.zooniverse.org/lab/4312

**Comment by eatyourgreens** [comment]
[This ADR](https://github.com/zooniverse/front-end-monorepo/blob/master/docs/arch/adr-11.md) maps `markdown-it` plugins (this library) to Remark (FEM.)

**Comment by eatyourgreens** [comment]
https://github.com/zooniverse/front-end-monorepo/pull/5352 fixes this by changing the markdown parser from Remark to `markdownz`.

**Comment by eatyourgreens** [comment]
Also noting that [remark-external-links](https://github.com/remarkjs/remark-external-links) is legacy and no longer supported.

**Comment by goplayoutside3** [comment]
Noting that as part of https://github.com/zooniverse/front-end-monorepo/pull/5352's change to `markdownz` in FEM, this means external links in markdown will no longer auto-open in a new tab. Instead, project teams need to use `+tab+` in links they want to open in a new tab.

As Jim brought up in the PR above, volunteers don't have a warning when links force-open a new tab, and this is an accessibility failure to be fixed in FEM. I've opened https://github.com/zooniverse/front-end-monorepo/issues/5530 for discussing solutions.

**Comment by eatyourgreens** [comment]
Are there any examples of projects with links in the project introduction?

**Comment by goplayoutside3** [comment]
I think this one does: https://frontend.preview.zooniverse.org/projects/zooniverse/mapping-change

<img width="601" alt="Screenshot 2023-10-26 at 1 02 50 PM" src="https://github.com/zooniverse/markdownz/assets/23665803/e6684a44-e60c-4386-bb13-8575722f33a9">
